name: 'Limit price check'
description: 'Check if limit event has occurred using current and previous price'
inputs:
  limit-price: # id of input
    description: 'Limit price to check'
    required: true
    default: '10'
  current-price: #id of input
    description: 'Current price to check against'
    required: true
    default: '12'
  previous-price: #id of input
   description: 'Previous price to check against'
   required: true
   default: '8'
outputs:
  time: # id of output
    description: 'The time we did the limit check'
  limit-event:
    description: 'Did a limit event occur or not'
runs:
  using: 'node12'
  main: 'index.js'
